server:
  port: 8082
  session:
    cookie:
      name: JSESSIONID2

#megaclient:
#  client:
##    id: megaclient
#    clientId: megaclient
#    clientSecret: 123456
##    accessTokenUri: http://localhost:8081/oauth/token
##    userAuthorizationUri: http://localhost:8081/oauth/authorize
#    tokenIntrospectionUri: http://localhost:8081/oauth/check_token
##    authenticationScheme: query
##    clientAuthenticationScheme: header
##    scope:
##      - user
##      - read
##      - write
##  resource:
##    userInfoUri: http://localhost:8081/api/user/principal.json
##    preferTokenInfo: true

logging:
  level:
    org.springframework.security: DEBUG